server {
    listen 80;
    server_name webPortfolio;

    location / {
        proxy_pass http://nextjs_app:3000; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /_next/static/ {
        proxy_pass http://nextjs_app:3000;
        proxy_buffering on;
        expires 365d;
    }
}